spring.application.name=workspace-hub

#Config do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/workspacehub
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver

#Config do hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Dados do jwt
spring.security.jwt.secret=oyuq87y2e987y2e49yahwduhi721yeolid
spring.security.jwt.issuer=Alex Baranoski Speck
spring.security.jwt.expires-at-min=60